#!/usr/bin/env php
<?php

define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH . '/vendor');

require_once CRAFT_VENDOR_PATH . '/autoload.php';

if (class_exists('Dotenv\Dotenv') && file_exists(CRAFT_BASE_PATH . '/.env')) {

	Dotenv\Dotenv::create(CRAFT_BASE_PATH)->load();

}

define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');

$app = require CRAFT_VENDOR_PATH . '/craftcms/cms/bootstrap/console.php';

$exitCode = $app->run();

exit($exitCode);
